cat << 'EOF' > ~/.config/hypr/hypridle.conf
general {
    lock_cmd = echo "locked"
    ignore_dbus_inhibit = false
}

# Правило для AFK (например, 300 секунд = 5 минут)
listener {
    timeout = 5killall hypridle 2>/dev/null; hypridle > /dev/null 2>&1 &
    on-timeout = touch /tmp/frog_afk
    on-resume = rm -f /tmp/frog_afk
}
EOF